### ISSUE TITLE
Add redirects 

### ISSUE THREAD

**Issue by bbenligiray** [api3dao/oev-docs#131]
Feels like https://docs.api3.org/dapps and https://docs.api3.org/oev-searchers should land somewhere rather than giving a 404. I'm not sure how that's done.

**Comment by cduarte3** [comment]
Hello @bbenligiray ik I was not assigned, but seeing as nobody has completed this issue yet, I pulled the issue to a fork and was able to make a minimal solution to resolve the problem.

I included redirects that will bring a user from /dapps to /dapps/overview automatically and from /oev-searchers to /oev-searchers/overview the same way.

I will be making a PR, please let me know if you would need anything else for this issue

**Comment by wkande** [comment]
There is no file `index.md` in the root of the `/dapp` or `/oev_searcher` folders. Probably a carry over from when these were part of `vitepress-docs`. Moving and renaming the current target files would be simple but then there is the risk of breaking external links. Not sure if anyone is calling these links outside of the API3 website.

**Comment by cduarte3** [comment]
Hello @wkande, I created the index.md files with the intent of allowing for the redirect Hope this cleared up any confusion with that. I am assuming this is okay, as I went through a lot of the links and nothing previously implemented was affected by my changes. All that was affected was the two 404 directed routes of /dapp and /oev-searchers now redirect to the proper pages that a user would look for as per the original request of the issue.

**Comment by wkande** [comment]
@cduarte3 yes that would work but there will most likely be screen flicker for the redirect. I will clone your repo and run it locally on Friday and see how it behaves.

The better solution is to move the pages you are redirecting to become the index.md file of the root of the URL. This, as I mentioned before, might be an issue in that external links that reference the current files will break. If the solution is not to move/rename the files then another solution is to add redirects to the file `https://github.com/api3dao/oev-docs/blob/main/firebase.json`. One would need to build the project and them run a local firebase instance to test it.

If I had my way I would move/rename the files and communicate with the owners of the external links.

**Comment by bbenligiray** [comment]
Thanks for the PR @cduarte3 . I'll have to agree with @wkande here, avoiding an explicit redirect would be ideal, the main objective is for these links to not 404.
